version: '3.8'

services:
  bitcoin-unconfirmed-transactions:
    build: .
    ports:
      - "8002"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bitcoin-unconfirmed-transactions
    ports:
      - "4001:4001"
