version: '3.8'

services:
  base-python-service-template:
    build: .
    ports:
      - "8001"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - base-python-service-template
    ports:
      - "4000:4000"
